dist: trusty
sudo: false
language: python

jobs:
  fast_finish: true
  include:
  - python: 2.7
  - python: &latest_py3 3.6
  - stage: deploy
    if: tag IS present
    python: *latest_py3
    install: skip
    script: skip
    deploy:
      provider: pypi
      on:
        tags: true
        all_branches: true
      user: jaraco
      # supply password with `travis encrypt --add deploy.password`
      distributions: dists
      skip_cleanup: true
      skip_upload_docs: true

cache: pip

install:
- pip install tox

script: tox
